# Site settings
title: Chowdown (with recipes from Timo)
email: no-reply@timo-reymann.de
description: The plain text recipe database for hackers (with my recipes)
# baseurl: "https://timo-reymann.github.io/recipes"
language: "de"
lang_direction: "ltr"
color: "#D65108"
twitter_username: timo_reymann
github_username:  timo-reymann

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  de:
    components: "Komponenten"
    ingredients: "Zutaten"
    directions: "Zubereitung"
    category: "Kategorie"
    nutritional_information: "Nährwertangaben"
    component_based: 'Dieses Rezept besteht aus <strong class="blue">mehreren Komponenten</strong>.'
    search: "Suche"
    searchHelp: "Suche nach Tags, oder Zutaten ..."
    blog: "Blog"
    subscribe: "Abonnieren"

sass:
  sass_dir: css