# Site settings
title: Chowdown
email: your-email@domain.com
description: The plain text recipe database for hackers
baseurl: "https://timo-reymann.github.io/chowdown/"
language: "de"
lang_direction: "ltr"
color: "#007FFF"
twitter_username: clarklab
github_username:  clarklab

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  de:
    components: "Komponenten"
    ingredients: "Zutaten"
    directions: "Zubereitung"
    category: "Kategorie"
    nutritional_information: "Nährwertangaben"
    component_based: 'Dieses Rezept besteht aus <strong class="blue">mehreren Komponenten</strong>.'
    search: "Suche"
    blog: "Blog"
    subscribe: "Abonnieren"
